-- Autocmds are automatically loaded on the VeryLazy event
-- Default autocmds that are always set: https://github.com/LazyVim/LazyVim/blob/main/lua/lazyvim/con***REMOVED***g/autocmds.lua
-- Add any additional autocmds here
