#! /bin/sh

polybar -r &
pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 2 3 4 5 6 7 8 9 10

setxkbmap -option grp:win_space_toggle ru,us &

bspc con***REMOVED***g border_width         2
bspc con***REMOVED***g window_gap          12

bspc con***REMOVED***g split_ratio          0.52
bspc con***REMOVED***g borderless_monocle   true
bspc con***REMOVED***g gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

feh --bg-***REMOVED***ll ~/.dot***REMOVED***les/wallpapers/musashi2.jpg
