bind = $mainMod, f, exec, $browser
bind = $mainMod, t, exec, $term
bind = $mainMod, q, exec, hyprctl dispatch killactive

# VIM focus keys
bind = $mainMod, h, movefocus, l
bind = $mainMod, l, movefocus, r
bind = $mainMod, j, movefocus, d
bind = $mainMod, k, movefocus, u

bind = $mainMod, a, exec, sh ~/.config/rofi/launchers/type-6/launcher.sh d
