bind = $mainMod, f, exec, $browser
bind = $mainMod, t, exec, $term
bind = $mainMod, q, exec, hyprctl dispatch killactive

# VIM focus keys
bind = $mainMod, h, movefocus, l
bind = $mainMod, l, movefocus, r
bind = $mainMod, j, movefocus, d
bind = $mainMod, k, movefocus, u

# VIM move window keys
bind = $mainMod+Shift, h, movewindow, l
bind = $mainMod+Shift, l, movewindow, r
bind = $mainMod+Shift, j, movewindow, d
bind = $mainMod+Shift, k, movewindow, u

bind = $mainMod, a, exec, sh ~/.config/rofi/launchers/type-6/launcher.sh

$screenPath = ~/Pictures/Screenshots
bind = , Print, exec, SCREEN_DIR=$screenPath sh ~/.config/scripts/fs_screenshot.sh
bind = Shift, Print, exec, SCREEN_DIR=$screenPath sh ~/.config/scripts/window_screenshot.sh
bind = Alt, Print, exec, SCREEN_DIR=$screenPath sh ~/.config/scripts/region_screenshot.sh

bind = , F6, exec, wpctl set-volume @DEFAULT_SINK@ 5%- --limit 1
bind = , F7, exec, wpctl set-volume @DEFAULT_SINK@ 5%+ --limit 1
