#!/bin/sh

currentdir=$(dirname $(realpath $0))
rootdir=$(dirname $currentdir)

echo Installing dependencies
sudo pacman -S $(cat $currentdir/packages.list)

echo Installing yay [AUR HELPER]
yayRepo=$HOME/yay
git clone https://aur.archlinux.org/yay.git $yayRepo && cd $yayRepo && makepkg -si && rm -rf $yayRepo && cd $rootdir

echo Installing AUR dependencies
sudo yay -S $(cat $currentdir/packages-aur.list)

# sddm
sddmThemesPath=/usr/share/sddm/themes
candypath=$sddmThemesPath/sugar-candy
sudo wget https://github.com/Kangie/sddm-sugar-candy/archive/refs/tags/v1.6.tar.gz -O $sddmThemesPath/sugar-candy.tar.gz
sudo tar xf $sddmThemesPath/sugar-candy.tar.gz --transform s/sddm-sugar-candy-1.6/sugar-candy/ -C $sddmThemesPath
sudo rm $sddmThemesPath/sugar-candy.tar.gz
sudo cp $rootdir/config/wallpapers/wp.jpg $candypath/Backgrounds
sudo cp $rootdir/sddm/sddm.conf /etc
sudo cp $rootdir/sddm/candy/theme.conf $candypath
sudo systemctl enable sddm
sudo systemctl start sddm
