#!/bin/sh

currentdir=$(dirname $(realpath $0))
rootdir=$(dirname $currentdir)

echo Installing dependencies
sudo pacman -S $(cat $currentdir/packages.list)

cat << EOF > ~/.xinitrc
    polybar -r &
    sxhkd &
    exec bspwm
EOF

apps=(alacritty nvim polybar bspwm sxhkd rofi betterlockscreen)

if [ ! -d ~/.config ]; then
    mkdir ~/.config
fi
echo Copying files into ~/.config
for app in "${apps[@]}"; do
    echo $app
    cp -r $rootdir/$app ~/.config/
done

wget https://raw.githubusercontent.com/polybar/polybar-scripts/master/polybar-scripts/player-mpris-tail/player-mpris-tail.py -O ~/.local/bin/player-mpris-tail.py
chmod +x ~/.local/bin/player-mpris-tail.py

# Zsh
echo Setting up ZSH
sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
cp $rootdir/zsh/.zshrc ~/.zshrc

# TPM
echo Setting up Tmux
git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
cp $rootdir/tmux/.tmux.conf ~/.tmux.conf
tmux source ~/.tmux.conf

betterlockscreen -u $rootdir/wallpapers/wp.jpg

sddm
sddmThemesPath=/usr/share/sddm/themes
candypath=$sddmThemesPath/sugar-candy
sudo wget https://github.com/Kangie/sddm-sugar-candy/archive/refs/tags/v1.6.tar.gz -O $sddmThemesPath/sugar-candy.tar.gz
sudo tar xf $sddmThemesPath/sugar-candy.tar.gz --transform s/sddm-sugar-candy-1.6/sugar-candy/ -C $sddmThemesPath
sudo rm $sddmThemesPath/sugar-candy.tar.gz
sudo cp $rootdir/wallpapers/wp.jpg $candypath/Backgrounds
sudo cp $rootdir/sddm/sddm.conf /etc
sudo cp $rootdir/sddm/candy/theme.conf $candypath
sudo systemctl enable sddm
sudo systemctl start sddm
