unbind = $mainMod, K
unbind = $mainMod, L
unbind = $mainMod, J

bindl = $mainMod, Space, exec, $scrPath/keyboardswitch.sh
bind = $mainMod, J, movefocus, d
bind = $mainMod, K, movefocus, u
bind = $mainMod, H, movefocus, l
bind = $mainMod, L, movefocus, r

bind = $mainMod+Shift, L, exec, swaylock
bind = $mainMod+Shift, J, togglesplit

input {
    kb_layout = us,ru
}

windowrulev2 = float,fullscreen,class:^(org.telegram.desktop)$,title:^(Media viewer)$
