[cursor.style]
blinking = "On"
shape = "Block"

[cursor.vi_mode_style]
blinking = "On"
shape = "Block"

[env]
TERM = "xterm-256color"

[font]
size = 13

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"
style = "Bold Italic"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[window]
dynamic_padding = true
padding = { x = 10, y = 10 }

[general]
live_config_reload = true

import = ["~/.config/alacritty/colorschemes/korea-lights.toml"]
