[cursor.style]
blinking = "On"
shape = "Block"

[cursor.vi_mode_style]
blinking = "On"
shape = "Block"

[env]
TERM = "xterm-256color"

[font.bold]
family = "Hack Nerd Font"
style = "Bold"

[font.bold_italic]
family = "Hack Nerd Font"
style = "Bold Italic"

[font.italic]
family = "Hack Nerd Font"
style = "Italic"

[font.normal]
family = "Hack Nerd Font"
style = "Regular"

[font]
size = 16

[window]
dynamic_padding = true
padding = { x = 5, y = 5 }
decorations = "none"
opacity = 0.82

[general]
live_config_reload = true

import = ["~/.config/alacritty/colorschemes/rose-pine-moon.toml"]
