"$schema" = 'https://starship.rs/config-schema.json'

format = "$character"
right_format = "$all"

add_newline = true

[character]
success_symbol = "[;- >](bold green)"
error_symbol = "[;- <](bold red)"

[package]
disabled = true
