"$schema" = 'https://starship.rs/config-schema.json'

format = "$username $character"
right_format = "$all"

add_newline = true

[username]
show_always = true
format = "[$user]($style)"

[character]
success_symbol = "[;- >](bold green)"
error_symbol = "[;- <](bold red)"

[package]
disabled = true
