# Colors (Ayu Dark)

# Default colors
[colors.primary]
background = '#1e2833'
foreground = '#ffffff'

# Normal colors
[colors.normal]
black = '#01060E'
red = '#EA6C73'
green = '#91B362'
yellow = '#F9AF4F'
blue = '#6573d0'
magenta = '#FAE994'
cyan = '#e6b3b1'
white = '#C7C7C7'

# Bright colors
[colors.bright]
black = '#2D3E4E'
red = '#F07178'
green = '#C2D94C'
yellow = '#FFB454'
blue = '#9488f7'
magenta = '#FFEE99'
cyan = '#F2BDBB'
white = '#FFFFFF'
